name: devpul_example
description: Example Flutter app using every DevPul package.
publish_to: none
version: 0.2.0

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  devpul: ^0.2.0
  devpul_dio: ^0.2.0
  devpul_flutter: ^0.2.0
  devpul_http: ^0.2.0
  dio: ^5.2.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
